<?php

/**
 * @file
 * Contains as_choose.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_choose_help($route_name, RouteMatchInterface $route_match) {
	  switch ($route_name) {
	    // Main module help for the as_choose module.
	    case 'help.page.as_choose':
	      $output = '';
	      $output .= '<h3>' . t('About') . '</h3>';
	      $output .= '<p>' . t('Chooses feature for AstonShop web site') . '</p>';
	      return $output;

	    default:
  }
}
/**
 * Implements hook_theme().
 * Register a module or theme's theme implementations.
*/
function as_choose_theme($existing, $type, $theme, $path) {
	  return array(
		    'choose_list' => array(
		    'render element' => 'elements',
	    ),
	    
	  );
}
